
Episode: 0 total_score: -25289.30664798819 Building_Score_1: -5462.445331985886 Building_Score_2: -5287.193497663543 Building_Score_3: -4534.072530920955 Building_Score_4: -5164.95721471506 Building_Score_5: -4840.638072702725
Traceback (most recent call last):
  File "/home/frozenwolf/Desktop/neurIPS/Hecker_rl/citylearn-2022-starter-kit/train.py", line 54, in <module>
    train_ddpg_mlp(env=env,state_dim=env.observation_space[0].shape[0]*5,action_dim=env.action_space[0].shape[0]*5,actor_lr=args.actor_lr,critic_lr=args.critic_lr,tau=args.tau,
  File "/home/frozenwolf/Desktop/neurIPS/Hecker_rl/citylearn-2022-starter-kit/drl_algo/train_util.py", line 108, in train_ddpg_mlp
    torch.save(actor.state_dict(),"{}ddpg-actor_mlp_actor-lr:{}_critic-lr:{}_gamma:{}_tau:{}.pth".format(path_checkpoint,actor_lr,critic_lr,gamma,tau))
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/frozenwolf/Desktop/neurIPS/Hecker_rl/checkpoint/ddpg-actor_mlp_actor-lr:0.0003_critic-lr:0.0003_gamma:0.99_tau:0.05.pth'